title: Coffee is Wonderful
author: Maeve Walsh
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 My next greatest novel is about the wonders of coffee. Not only will I talk
 about the science behind the greatest caffeinated beverage that exists,
 but I'll also provide you with some at-home recipes for brewing a cup!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
